EMOTICONS = {":‑)": "happy",
             ":)": "happy",
             ":-]": "happy",
             ":]": "happy",
             ":-3": "happy",
             ":3": "happy",
             ":->": "happy",
             ":>": "happy",
             "8-)": "happy",
             "8)": "happy",
             ":-}": "happy",
             ":}": "happy",
             ":o)": "happy",
             ":c)": "happy",
             ":^)": "happy",
             "=]": "happy",
             "=)": "happy",
             ":‑D": "laughing",
             ":D": "laughing",
             "8‑D": "laughing",
             "8D": "laughing",
             "x‑D": "laughing",
             "xD": "laughing",
             "X‑D": "laughing",
             "XD": "laughing",
             "=D": "laughing",
             "=3": "laughing",
             "B^D": "laughing",
             ":‑(": "sad",
             ":(": "sad",
             ":‑c": "sad",
             ":c": "sad",
             ":‑<": "sad",
             ":<": "sad",
             ":‑[": "sad",
             ":[": "sad",
             ":-||": "sad",
             ">:[": "angry",
             ":{": "sad",
             ":@": "sad",
             ";(": "sad",
             ":'‑(": "crying",
             ":'(": "crying",
             ":'‑)": "happy",
             ":')": "happy",
             "D‑':": "sadness",
             "D:<": "sadness",
             "D:": "sadness",
             "D8": "sadness",
             "D;": "sadness",
             "D=": "sadness",
             "DX": "sadness",
             ":‑O": "surprise",
             ":O": "surprise",
             ":‑o": "surprise",
             ":o": "surprise",
             ":-0": "surprise",
             "8‑0": "surprise",
             ">:O": "surprise",
             ":-*": "kiss",
             ":*": "kiss",
             ":×": "kiss",
             ";‑)": "wink",
             ";)": "wink",
             "*-)": "wink",
             "*)": "wink",
             ";‑]": "wink",
             ";]": "wink",
             ";^)": "wink",
             ":‑,": "wink",
             ";D": "wink",
             ":‑P": "playful",
             ":P": "playful",
             "X‑P": "playful",
             "XP": "playful",
             "x‑p": "playful",
             "xp": "playful",
             ":‑p": "playful",
             ":p": "playful",
             ":‑b": "playful",
             ":b": "playful",
             "d:": "playful",
             "=p": "playful",
             ">:P": "playful",
             ":‑/": "annoyed",
             ":/": "annoyed",
             ":‑.": "annoyed",
             ">:\\": "annoyed",
             ">:/": "annoyed",
             ":\\": "annoyed",
             "=/": "annoyed",
             """=\\""": "annoyed",
             ":L": "annoyed",
             "=L": "annoyed",
             ":S": "annoyed",
             ":‑|": "indecision",
             ":|": "indecision",
             ":$": "embarrassed",
             "://)": "embarrassed",
             "://3": "embarrassed",
             ":‑X": "silent",
             ":X": "silent",
             ":‑#": "silent",
             ":#": "silent",
             ":‑&": "silent",
             ":&": "silent",
             "O:‑)": "saint",
             "O:)": "saint",
             "0:‑3": "saint",
             "0:3": "saint",
             "0:‑)": "saint",
             "0:)": "saint",
             "0;^)": "saint",
             ">:‑)": "evil",
             "}:‑)": "evil",
             "}:)": "evil",
             "3:‑)": "evil",
             "3:)": "evil",
             ">;)": "evil",
             ">:3": "evil",
             ";3": "evil",
             "|;‑)": "cool",
             "|‑O": "cool",
             "%‑)": "confused",
             "%)": "confused",
             ":‑###..": "sick",
             ":###..": "sick",
             "<:‑|": "dumb",
             "',:-|": "scepticism",
             "',:-l": "scepticism"}


def parse_emoticons(text):
    words = text.split()
    pre_words = [EMOTICONS[word] if word in EMOTICONS.keys() else word for word in words]
    return " ".join([word for word in pre_words])


def show_emticons():
    for key, item in EMOTICONS.items():
        print(f"{key} = {item}")


def main():
    print(parse_emoticons("Wow! Busy day! :) :) :)"))


if __name__ == '__main__':
    main()
